// `npm run firms:author -- [--firm <slug>|all] [--write] [--dry-run]` — authors 10–15 interview
// questions per firm with Opus 5 (structured output, cached prompt) from the firm's dossier.
// Live output goes to .eval/firms/<slug>.json (gitignored) unless --write, which replaces
// fixtures/firms/questions/<slug>.json. Everything it produces is loaded by `seed -- 08` as
// status=generated with recency_year=null and empty sources (no fake provenance).
// Without API credit (or with --dry-run) it prints `NO API CREDIT — fixture questions` and reports
// the committed fixture files instead, so the pipeline is verifiable offline.
import { config as loadEnv } from "dotenv";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { betaZodOutputFormat } from "@anthropic-ai/sdk/helpers/beta/zod";
import { MODEL_CHAT, OPUS_BETAS, OPUS_FALLBACKS, getClient } from "../../src/lib/ai/client";
import { isCredentialFailure, probeApi } from "../../src/lib/ai/probe";
import { firmQuestionsPrompt } from "../../src/lib/ai/prompts/firm-questions.v1";
import { AuthoredQuestionsSchema, FirmQuestionFileSchema, type Firm, type FirmQuestion } from "../../src/lib/firms/schema";
import { loadFirmFixtures, loadQuestionFixture, QUESTIONS_DIR } from "./fixtures";

loadEnv({ path: ".env.local" });

export const FIRM_PROMPT_VERSION = `${firmQuestionsPrompt.id}.v${firmQuestionsPrompt.version}`;

export function renderDossier(f: Firm): string {
  return [
    `<firm slug="${f.slug}">`,
    `name: ${f.name}`,
    `type: ${f.type}`,
    f.founded ? `founded: ${f.founded}` : "",
    f.hq ? `hq: ${f.hq}` : "",
    f.scale_note ? `scale: ${f.scale_note}` : "",
    `divisions: ${f.divisions.join("; ") || "(unknown)"}`,
    `values: ${f.values.join("; ") || "(unknown)"}`,
    `process: ${f.process.map((p) => `${p.stage}${p.when ? ` (${p.when})` : ""}`).join(" → ") || "(unknown)"}`,
    "</firm>",
  ].filter(Boolean).join("\n");
}

/** Converts a live structured output into fixture-file rows (no provenance). */
export function toFixtureQuestions(parsed: unknown): FirmQuestion[] {
  const r = AuthoredQuestionsSchema.safeParse(parsed);
  if (!r.success) throw new Error(`authored questions failed schema: ${r.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join("; ")}`);
  return r.data.questions.map((q) => ({ ...q, division: q.division?.trim() || null, question: q.question.trim(), guidance_md: q.guidance_md.trim(), recency_year: null, sources: [] }));
}

export async function authorLive(f: Firm): Promise<{ questions: FirmQuestion[]; usage: { input: number; output: number; cache_read: number } }> {
  const res = await getClient().beta.messages.parse({
    model: process.env.CONTENT_MODEL || MODEL_CHAT,
    max_tokens: 8000,
    betas: [...OPUS_BETAS],
    fallbacks: OPUS_FALLBACKS,
    output_config: { effort: "high", format: betaZodOutputFormat(AuthoredQuestionsSchema) },
    system: [{ type: "text", text: firmQuestionsPrompt.system, cache_control: { type: "ephemeral" } }],
    messages: [{ role: "user", content: renderDossier(f) }],
  });
  if (res.stop_reason === "refusal") throw new Error(`authoring refused (${res.stop_details?.category ?? "unknown"})`);
  return { questions: toFixtureQuestions(res.parsed_output), usage: { input: res.usage.input_tokens, output: res.usage.output_tokens, cache_read: res.usage.cache_read_input_tokens ?? 0 } };
}

async function main() {
  const args = process.argv.slice(2);
  const firmArg = args.includes("--firm") ? args[args.indexOf("--firm") + 1] : "all";
  const write = args.includes("--write");
  const dry = args.includes("--dry-run");
  const firms = loadFirmFixtures().filter((f) => firmArg === "all" || f.slug === firmArg);
  if (!firms.length) throw new Error(`no firm fixture matches ${firmArg}`);

  const probe = dry ? null : await probeApi();
  if (!probe || !probe.ok) {
    if (probe && !isCredentialFailure(probe)) console.warn(`firms:author: API probe failed (${probe.reason}: ${probe.message})`);
    console.log(dry ? "DRY RUN — fixture questions" : "NO API CREDIT — fixture questions");
    let total = 0;
    for (const f of firms) {
      const qs = loadQuestionFixture(f.slug);
      console.log(`  ${f.slug}: ${qs ? `${qs.length} fixture questions` : "NO FIXTURE"}`);
      total += qs?.length ?? 0;
    }
    console.log(`fixtures: ${firms.length} firms, ${total} questions (loaded as generated by \`npm run seed -- 08\`)`);
    return;
  }

  const outDir = write ? QUESTIONS_DIR : path.join(process.cwd(), ".eval", "firms");
  mkdirSync(outDir, { recursive: true });
  for (const f of firms) {
    const t0 = Date.now();
    const { questions, usage } = await authorLive(f);
    const file = { _note: `Authored by ${FIRM_PROMPT_VERSION} on ${new Date().toISOString().slice(0, 10)} from the firm's dossier. No provenance is claimed (recency_year null, sources empty). Loaded as status=generated.`, firm: f.slug, questions };
    FirmQuestionFileSchema.parse(file);
    const p = path.join(outDir, `${f.slug}.json`);
    writeFileSync(p, `${JSON.stringify(file, null, 2)}\n`);
    console.log(`${f.slug}: ${questions.length} questions → ${path.relative(process.cwd(), p)} (${((Date.now() - t0) / 1000).toFixed(1)} s, in ${usage.input} / cached ${usage.cache_read} / out ${usage.output})${existsSync(p) ? "" : " (write failed)"}`);
  }
}

if (require.main === module) {
  main().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
